services:
  - type: web
    name: paws-api
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PGSSL
        value: "true"
      - key: PORT
        value: "4000"
