# Render Blueprint for API + Managed Postgres (free tier safe)
databases:
  - name: paws-db
    plan: free

services:
  - type: web
    name: paws-api
    runtime: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paws-db
          property: connectionString
      - key: PGSSL
        value: "true"
      - key: PORT
        value: "4000"
      - key: SEED_ON_BOOT
        value: "true"
